---
# Source: airflow/templates/secrets/extra-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "airflow-airflow-connections"
  labels:
    release: airflow
    chart: "airflow-1.2.0"
    heritage: Helm
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
data:
  AIRFLOW_CONN_AWS: ''
