---
# Source: airflow/templates/scheduler/scheduler-deployment.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

################################
## Airflow Scheduler Deployment/StatefulSet
#################################

# Are we using a local executor?
# Is persistence enabled on the _workers_?
# This is important because in $local mode, the scheduler assumes the role of the worker
# If we're using a StatefulSet
# If we're using elasticsearch logging

kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow-scheduler
  labels:
    tier: airflow
    component: scheduler
    release: airflow
    chart: "airflow-1.2.0"
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: airflow
      component: scheduler
      release: airflow
  template:
    metadata:
      labels:
        tier: airflow
        component: scheduler
        release: airflow
      annotations:
        checksum/metadata-secret: dcbb26b06a9d686bf5fedceff6d4024447053fded58a37271cdfef14f8c8c800
        checksum/result-backend-secret: 81fd0bc85dc6b240d98a984a508d94f010a012348f2ce63d2a262b0cbc6e0356
        checksum/pgbouncer-config-secret: da52bd1edfe820f0ddfacdebb20a4cc6407d296ee45bcb500a6407e2261a5ba2
        checksum/airflow-config: aea4f92ef86c687e5d97ba4bdb0b444a5ba44300ce2d568b1c1b554e87d799c8
        checksum/extra-configmaps: 2e44e493035e2f6a255d08f8104087ff10d30aef6f63176f1b18f75f73295598
        checksum/extra-secrets: bb91ef06ddc31c0c5a29973832163d8b0b597812a793ef911d33b622bc9d1655
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      nodeSelector:
        {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  component: scheduler
              topologyKey: kubernetes.io/hostname
            weight: 100
      tolerations:
        []
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      serviceAccountName: airflow-scheduler
      securityContext:
        runAsUser: 50000
        fsGroup: 0
      initContainers:
        - name: wait-for-airflow-migrations
          resources:
            {}
          image: apache/airflow:2.1.4
          imagePullPolicy: IfNotPresent
          args:          
            
            - python
            - -c
            - |
                  import airflow
                  import logging
                  import os
                  import time
          
                  from alembic.config import Config
                  from alembic.runtime.migration import MigrationContext
                  from alembic.script import ScriptDirectory
          
                  from airflow import settings
          
                  package_dir = os.path.abspath(os.path.dirname(airflow.__file__))
                  directory = os.path.join(package_dir, 'migrations')
                  config = Config(os.path.join(package_dir, 'alembic.ini'))
                  config.set_main_option('script_location', directory)
                  config.set_main_option('sqlalchemy.url', settings.SQL_ALCHEMY_CONN.replace('%', '%%'))
                  script_ = ScriptDirectory.from_config(config)
          
                  timeout=60
          
                  with settings.engine.connect() as connection:
                      context = MigrationContext.configure(connection)
                      ticker = 0
                      while True:
                          source_heads = set(script_.get_heads())
          
                          db_heads = set(context.get_current_heads())
                          if source_heads == db_heads:
                              break
          
                          if ticker >= timeout:
                              raise TimeoutError("There are still unapplied migrations after {} seconds.".format(ticker))
                          ticker += 1
                          time.sleep(1)
                          logging.info('Waiting for migrations... %s second(s)', ticker)
          envFrom:          
            []
          env:          
            # Dynamically created environment variables
            # Dynamically created secret envs
            - name: AIRFLOW_CONN_AWS
              valueFrom:
                secretKeyRef:
                  name: my-airflow-connections
                  key: AIRFLOW_CONN_AWS
            # Extra env          
            # Hard Coded Airflow Envs
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-fernet-key
                  key: fernet-key
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-airflow-metadata
                  key: connection
            - name: AIRFLOW_CONN_AIRFLOW_DB
              valueFrom:
                secretKeyRef:
                  name: airflow-airflow-metadata
                  key: connection
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-webserver-secret-key
                  key: webserver-secret-key
            - name: AIRFLOW__CELERY__CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: airflow-airflow-result-backend
                  key: connection
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: airflow-airflow-result-backend
                  key: connection
            - name: AIRFLOW__CELERY__BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: airflow-broker-url
                  key: connection
        
        - name: git-sync-init
          image: k8s.gcr.io/git-sync/git-sync:v3.3.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 65533
          env:
            - name: GIT_SYNC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "git-credentials"
                  key: GIT_SYNC_USERNAME
            - name: GIT_SYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "git-credentials"
                  key: GIT_SYNC_PASSWORD
            - name: GIT_SYNC_REV
              value: "HEAD"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_REPO
              value: "https://github.com/CoterieAI/regulatoryai.git"
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_ROOT
              value: "/git"
            - name: GIT_SYNC_DEST
              value: "repo"
            - name: GIT_SYNC_ADD_USER
              value: "true"
            - name: GIT_SYNC_WAIT
              value: "60"
            - name: GIT_SYNC_MAX_SYNC_FAILURES
              value: "5"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
          resources: 
              {}
          volumeMounts:
          - name: dags
            mountPath: /git
      containers:
        # Always run the main scheduler container.
        - name: scheduler
          image: apache/airflow:2.1.4
          imagePullPolicy: IfNotPresent
          args: 
            - bash
            - -c
            - exec airflow scheduler
          envFrom:          
            []
          env:          
            # Dynamically created environment variables
            # Dynamically created secret envs
            - name: AIRFLOW_CONN_AWS
              valueFrom:
                secretKeyRef:
                  name: my-airflow-connections
                  key: AIRFLOW_CONN_AWS
            # Extra env          
            # Hard Coded Airflow Envs
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-fernet-key
                  key: fernet-key
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-airflow-metadata
                  key: connection
            - name: AIRFLOW_CONN_AIRFLOW_DB
              valueFrom:
                secretKeyRef:
                  name: airflow-airflow-metadata
                  key: connection
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-webserver-secret-key
                  key: webserver-secret-key
            - name: AIRFLOW__CELERY__CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: airflow-airflow-result-backend
                  key: connection
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: airflow-airflow-result-backend
                  key: connection
            - name: AIRFLOW__CELERY__BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: airflow-broker-url
                  key: connection
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
            periodSeconds: 30
            exec:
              command:
              - /entrypoint
              - python
              - -Wignore
              - -c
              - |
                import os
                os.environ['AIRFLOW__CORE__LOGGING_LEVEL'] = 'ERROR'
                os.environ['AIRFLOW__LOGGING__LOGGING_LEVEL'] = 'ERROR'

                from airflow.jobs.scheduler_job import SchedulerJob
                from airflow.utils.db import create_session
                from airflow.utils.net import get_hostname
                import sys

                with create_session() as session:
                    job = session.query(SchedulerJob).filter_by(hostname=get_hostname()).order_by(
                        SchedulerJob.latest_heartbeat.desc()).limit(1).first()

                sys.exit(0 if job.is_alive() else 1)
          resources:
            {}
          volumeMounts:
            - name: config
              mountPath: /opt/airflow/pod_templates/pod_template_file.yaml
              subPath: pod_template_file.yaml
              readOnly: true
            - name: logs
              mountPath: "/opt/airflow/logs"
            - name: config
              mountPath: "/opt/airflow/airflow.cfg"
              subPath: airflow.cfg
              readOnly: true
            - name: config
              mountPath: "/opt/airflow/config/airflow_local_settings.py"
              subPath: airflow_local_settings.py
              readOnly: true
            - name: dags
              mountPath: /opt/airflow/dags
              readOnly: True        
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.3.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 65533
          env:
            - name: GIT_SYNC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "git-credentials"
                  key: GIT_SYNC_USERNAME
            - name: GIT_SYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "git-credentials"
                  key: GIT_SYNC_PASSWORD
            - name: GIT_SYNC_REV
              value: "HEAD"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_REPO
              value: "https://github.com/CoterieAI/regulatoryai.git"
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_ROOT
              value: "/git"
            - name: GIT_SYNC_DEST
              value: "repo"
            - name: GIT_SYNC_ADD_USER
              value: "true"
            - name: GIT_SYNC_WAIT
              value: "60"
            - name: GIT_SYNC_MAX_SYNC_FAILURES
              value: "5"
          resources: 
              {}
          volumeMounts:
          - name: dags
            mountPath: /git
        - name: scheduler-log-groomer
          resources:
            {}
          image: apache/airflow:2.1.4
          imagePullPolicy: IfNotPresent
          args: 
            - bash
            - /clean-logs
          
          env:
            - name: AIRFLOW__LOG_RETENTION_DAYS
              value: "15"
          volumeMounts:
            - name: logs
              mountPath: "/opt/airflow/logs"
      volumes:
        - name: config
          configMap:
            name: airflow-airflow-config
        - name: dags
          emptyDir: {}
        - name: logs
          emptyDir: {}
